spring:
  application:
    name: users
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=MySQL;NON_KEYWORDS=users,orders,user;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    change-log: classpath:/liquibase/changelog.yml
  mail:
    host: smtp.gmail.com
    port: 587
    username: benny.noreply@gmail.com
    password: qwerty123!@#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8086

mail:
  admin: benny.noreply@gmail.com

